
pandemonium_branch = 'master'

engine_repository = [ ['https://github.com/Relintai/pandemonium_engine.git', 'git@github.com:Relintai/pandemonium_engine.git'], 'pandemonium_engine', '' ]

module_repositories = [
]

removed_modules = [
]

addon_repositories = [
]

third_party_addon_repositories = [
]

custom_module_folders = ""

slim_args = 'disable_3d=yes module_bmp_enabled=no module_broken_seals_module_enabled=no module_cscript_enabled=no module_cvtt_enabled=no module_database_enabled=no module_dds_enabled=no module_enet_enabled=no module_entity_spell_system_enabled=no module_fastnoise_enabled=no module_hdr_enabled=no module_http_server_simple_enabled=no module_jpg_enabled=no module_material_maker_enabled=no module_mesh_data_resource_enabled=no module_mesh_utils_enabled=no module_minimp3_enabled=no module_network_synchronizer_enabled=no module_ogg_enabled=no module_opensimplex_enabled=no module_opus_enabled=no module_props_enabled=no module_props_2d_enabled=no module_pvr_enabled=no module_regex_enabled=no module_rtile_map_enabled=no module_skeleton_2d_enabled=no module_skeleton_3d_enabled=no module_squish_enabled=no module_stb_vorbis_enabled=no module_svg_enabled=no module_terraman_enabled=no module_terraman_2d_enabled=no module_texture_packer_enabled=no module_tga_enabled=no module_theora_enabled=no module_thread_pool_enabled=no module_ui_extensions_enabled=no module_upnp_enabled=no module_users_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_voxelman_enabled=no module_web_enabled=no module_websocket_enabled=no module_wfc_enabled=no'
#slim_args_editor = 'module_gltf_enabled=no module_bmp_enabled=no module_broken_seals_module_enabled=no module_cscript_enabled=no module_cvtt_enabled=no module_database_enabled=no module_dds_enabled=no module_enet_enabled=no module_entity_spell_system_enabled=no module_fastnoise_enabled=no module_hdr_enabled=no module_http_server_simple_enabled=no module_jpg_enabled=no module_material_maker_enabled=no module_mesh_data_resource_enabled=no module_mesh_utils_enabled=no module_minimp3_enabled=no module_network_synchronizer_enabled=no module_ogg_enabled=no module_opensimplex_enabled=no module_opus_enabled=no module_props_enabled=no module_props_2d_enabled=no module_pvr_enabled=no module_rtile_map_enabled=no module_skeleton_2d_enabled=no module_skeleton_3d_enabled=no module_squish_enabled=no module_stb_vorbis_enabled=no module_terraman_enabled=no module_terraman_2d_enabled=no module_texture_packer_enabled=no module_tga_enabled=no module_theora_enabled=no module_thread_pool_enabled=no module_ui_extensions_enabled=no module_upnp_enabled=no module_users_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_voxelman_enabled=no module_web_enabled=no module_websocket_enabled=no module_wfc_enabled=no'

#minizip=false
#module_navigation_enabled=no
#disable_advanced_gui=yes 